app: app-name
replicaCount: 1

cloud:
  service: myservice
  project: devision-io

image:
  repository: user/repo
  tag: tag
  pullPolicy: Always
  volume:
    enabled: true
    path: /tmp
  env:
  - key: ENV
    value: dev
  - key: SOME_KEY
    value: 1

prometheus_metrics: false

service:
  type: ClusterIP
  # Порт через который будет доступен контейнер 
  externalPort: 80
  # Порт который слушает приложение в контейнере
  internalPort: 80
  # Порт который будет использоватся для сбора метрик
  metricsPort: 8443
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - host: example.local
    - host: example.local_2
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  limits:
#    cpu: 500m
#    memory: 1Gi
#  requests:
#    cpu: 500m
#    memory: 512Mi
